services:
  smart-sampler-api:
    build: .
    container_name: smart-sampler-api
    restart: unless-stopped
    environment:
      - ROBYN_HOST=0.0.0.0
      - ROBYN_PORT=8080
    env_file:
      - .env
    volumes:
      - .:/app